[package]
name = "RandomCient"
version = "0.1.0"
edition = "2024"

[dependencies]
scapi = { git = "https://github.com/N-010/scapi", version = "0.2.5" }
async-trait = "0.1"
base64 = "0.22"
clap = { version = "4", features = ["derive"] }
crossterm = "0.29"
rand_core = "0.6.4"
ratatui = "0.30"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
tiny-keccak = { version = "2", features = ["k12"] }
