[package]
name = "RandomCient"
version = "0.1.0"
edition = "2024"

[dependencies]
scapi = { git = "https://github.com/N-010/scapi" }
async-trait = "0.1"
clap = { version = "4", features = ["derive"] }
rand = { version = "0.8" }
rand_core = "0.6.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
tiny-keccak = { version = "2", features = ["k12"] }
crossterm = "0.29"