[package]
name = "RandomCient"
version = "0.1.0"
edition = "2024"

[dependencies]
scapi = { git = "https://github.com/N-010/scapi" }
async-trait = "0.1"
blake3 = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tiny-keccak = { version = "2", features = ["k12"] }
anyhow = "1.0.100"
crossterm = "0.27"
